<?php
/**
 * The main template file
 * This is the most generic template file in a WordPress theme
 * and one of the two required files for a theme (the other being style.css).
 * It is used to display a page when nothing more specific matches a query.
 * E.g., it puts together the home page when no home.php file 
 *
 * Please see /external/starkers-utilities.php for info on Starkers_Utilities::get_template_parts()
 *
 * @package   WordPress
 * @subpackage  Abraham Lincoln
 * @since     Abraham Lincoln 0.1.0
 */
?>
<?php Starkers_Utilities::get_template_parts( array( 'parts/shared/html-header', 'parts/shared/header' ) ); ?>
  <!-- Post info in the image part will not work yet, because it is not a loop -->
  <?php
    //86 is the category ID for slideshows
    // $args = array( 'numberposts' => '3', 'category' => 86, );
    // $recent_posts = wp_get_recent_posts( $args );

    $category = 86;
    $excluded_categories = (87);
    $args = array(
        'category' => $category,
        'category__not_in' => $excluded_categories
    );

    $top_posts = get_posts($args);
      //image for the first one
    //echo '<li><a href="' . get_permalink($recent[0]["ID"]) . '" title="Look '.esc_attr($recent[0]["post_title"]).'" ><strong>' .   $recent[0]["post_title"].'</strong>By ' .   $recent[0]["post_author"].'</a> </li> ';
  ?>
      <div class="row">
          <div class="row content">
          <?php
            $count = 0;
            foreach ($top_posts as $post) {
          ?>
            <div class="col-md-<?php echo ($count == 0) ? '7' : '5'; ?>">
              <div class="relative">
                <img src="<? echo arg_photo($post, 628, '', '', true); ?>">
                <div class="on-top white-top">
                <h2><span><a href="<?php esc_url( the_permalink() ); ?>" title="Permalink to <?php the_title(); ?>" rel="bookmark"><?php the_title(); ?></a><span></h2>
                <h4><span><?php the_date(); ?> <?php the_time_ago(); ?> <? echo abraham_get_author(false); ?></span></h4>
              </div>
              </div>
              <?php if($count == 0) { ?>
              <p><?php echo abraham_excerpt(); ?> </p>
              <?php } ?>
            </div>
          <?php
            $count++; 
            } 
          ?>
          </div>
      </div>

<?php
$first_row = array(
  array("section" => "News",    "id" => 3),
  array("section" => "Features","id" => 4),
  array("section" => "Sports",  "id" => 5),
  array("section" => "Arts",    "id" => 6)
);
$second_row = array(
  array("section" => "Wespeaks","id" => 13),
  array("section" => "Opinion", "id" => 16),
  array("section" => "Food",    "id" => 75)
  //the fourth column is the PDF viewer
);
//columns should be generated by loops
?>
      <div class="row">
        <?php
          foreach ($first_row as $column) {
        ?>
        <div class="col-md-3">
          <div class="box">
            <h2><a href="<?php echo esc_url(get_category_link($column["id"])); ?>"><?php echo $column["section"]; ?></a></h2>
            <ul>
    				<?php
    					$args = array( 'numberposts' => '3', 'category' => $column["id"], );
    					$recent_posts = wp_get_recent_posts( $args );
    					foreach( $recent_posts as $recent ){
                //image for the first one
    						echo '<li><a href="' . get_permalink($recent["ID"]) . '" title="Look '.esc_attr($recent["post_title"]).'" ><strong>' .   $recent["post_title"].'</strong></a>' . abraham_get_author(true) . '</li> ';
    					}
    				?>
            </ul>
          </div>
        </div>
        <?php
          }
        ?>
      </div>
      <div class="row">
        <?php
          foreach ($second_row as $column) {
        ?>
        <div class="col-md-3">
          <div class="box">
            <h2><a href="<?php echo esc_url(get_category_link($column["id"])); ?>"><?php echo $column["section"]; ?></a></h2>
            <ul>
				<?php
					$args = array( 'numberposts' => '3', 'category' => $column["id"], );
					$recent_posts = wp_get_recent_posts( $args );
					foreach( $recent_posts as $recent ){
						echo '<li><a href="' . get_permalink($recent["ID"]) . '" title="Look '.esc_attr($recent["post_title"]).'" ><strong>' .   $recent["post_title"].'</strong>' . abraham_get_author(true). '</li> ';
					}
				?>
            </ul>
          </div>
        </div>
        <?php
          }
        ?>
        <div class="col-md-3">
          <div class="box pdf-box">
            <h2>PDF Viewer</h2>
          </div>
        </div>
      </div>

<?php Starkers_Utilities::get_template_parts( array( 'parts/shared/footer','parts/shared/html-footer') ); ?>