<?php
/**
 * The main template file
 * This is the most generic template file in a WordPress theme
 * and one of the two required files for a theme (the other being style.css).
 * It is used to display a page when nothing more specific matches a query.
 * E.g., it puts together the home page when no home.php file 
 *
 * Please see /external/starkers-utilities.php for info on Starkers_Utilities::get_template_parts()
 *
 * @package   WordPress
 * @subpackage  Abraham Lincoln
 * @since     Abraham Lincoln 0.1.0
 */
?>
<?php Starkers_Utilities::get_template_parts( array( 'parts/shared/html-header', 'parts/shared/header' ) ); ?>
<?php
$first_row = array(
  array("section" => "News",    "id" => 3),
  array("section" => "Features","id" => 4),
  array("section" => "Sports",  "id" => 5),
  array("section" => "Arts",    "id" => 6)
);
$second_row = array(
  array("section" => "Wespeaks","id" => 13),
  array("section" => "Opinion", "id" => 16),
  array("section" => "Food",    "id" => 75)
  //the fourth column is the PDF viewer
);
//columns should be generated by loops
?>
      <div class="row">
        <?php
          foreach ($first_row as $column) {
        ?>
        <div class="col-md-3">
          <div class="box">
            <h2><a href="<?php echo esc_url(get_category_link($column["id"])); ?>"><?php echo $column["section"]; ?></a></h2>
            <ul>
    				<?php
    					$args = array( 'numberposts' => '3', 'category' => $column["id"], );
    					$recent_posts = wp_get_recent_posts( $args );
    					foreach( $recent_posts as $recent ){
                //image for the first one
    						echo '<li><a href="' . get_permalink($recent["ID"]) . '" title="Look '.esc_attr($recent["post_title"]).'" ><strong>' .   $recent["post_title"].'</strong>By ' .   $recent["post_author"].'</a> </li> ';
    					}
    				?>
            </ul>
          </div>
        </div>
        <php
          }
        ?>
      </div>
      <div class="row">
        <?php
          foreach ($second_row as $column) {
        ?>
        <div class="col-md-3">
          <div class="box">
            <h2><a href="<?php echo esc_url(get_category_link($column["id"])); ?>"><?php echo $column["section"]; ?></a></h2>
            <ul>
				<?php
					$args = array( 'numberposts' => '3', 'category' => $column["id"], );
					$recent_posts = wp_get_recent_posts( $args );
					foreach( $recent_posts as $recent ){
						echo '<li><a href="' . get_permalink($recent["ID"]) . '" title="Look '.esc_attr($recent["post_title"]).'" ><strong>' .   $recent["post_title"].'</strong>By ' .   $recent["post_author"].'</a> </li> ';
					}
				?>
            </ul>
          </div>
        </div>
        <php
          }
        ?>
        <div class="col-md-3">
          <div class="box pdf-box">
            <h2>PDF Viewer</h2>
          </div>
        </div>
      </div>

<?php Starkers_Utilities::get_template_parts( array( 'parts/shared/footer','parts/shared/html-footer') ); ?>